config/routes.rb
Rails.application.routes.draw do
  namespace :backoffice do
    root to: 'backoffice#index'
    resources :users, path: "administrators"
    resources :clients, path: "customers"
    resources :welcomes, path: "products_text"
    resources :graphs, path: "landing_page"
    resources :partners
    resources :plans
    resources :contact_infos, path: "contact"
    resources :addresses
    resources :members, path: "staff"
    resources :services, path: "products"
    resources :another_services, path: "staff_text"
    get '/dashboard', to: redirect('/backoffice'), as: 'redirect'
    post '/dashboard', to: 'backoffice#dashboard', as: 'dashboard'
  end

  namespace :backoffice do
    post '/clients/:id/block', to: 'clients#block', as: 'client_block'
    post '/welcomes/:id/activate', to: 'welcomes#activate', as: 'welcome_activate'
    post '/graphs/:id/activate', to: 'graphs#activate', as: 'graph_activate'
    post '/partners/:id/activate', to: 'partners#activate' , as: 'partner_activate'
    post '/plans/:id/activate', to: 'plans#activate', as: 'plan_activate'
    post '/contact_infos/:id/activate', to: 'contact_infos#activate', as: 'contact_info_activate'
    post '/addresses/:id/activate', to: 'addresses#activate', as: 'address_activate'
  end

  resources :dashboard, only: [:show]
  get '/dashboard', to: redirect('/')
  post '/dashboard/:id', to: 'dashboard#auth', as: 'dashboard_auth'
  get '/dashboard/:id/authentication_failed', to: 'dashboard#authentication_failed', as: 'dashboard_authentication_failed'

  devise_for :users

  get '/example', to: 'dashboard#example', as: 'dashboard_example'

  resources :contacts, only: [:create]

  root to: 'home#index'
  get '/curso', to: 'home#page2', as: 'home_curso'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/anotherservice.rb
class Anotherservice < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :emails, dependent: :destroy

  accepts_nested_attributes_for :emails, reject_if: :all_blank, allow_destroy: true

  private

  def send_confirmation
    ClientsMailer.with(client: self).create_client.deliver_later
  end
end

app/models/contact.rb
class Contact < MailForm::Base
    attribute :name,         :validate => true
    attribute :email,        :validate => true
    attribute :phone,        :validate => true
    attribute :message,      :validate => true
    attribute :nickname,     :captcha  => true

    def headers
        {
            :subject => "[CONTATO]",
            :to => "falecom@filterfeed.com.br",
            :from => %("#{name}" <#{email}>)
        }
    end
end

app/models/contact_info.rb
class ContactInfo < ApplicationRecord
end

app/models/email.rb
class Email < ApplicationRecord
  belongs_to :client
end

app/models/graph.rb
class Graph < ApplicationRecord
end

app/models/member.rb
class Member < ApplicationRecord
  has_one_attached :avatar
end

app/models/partner.rb
class Partner < ApplicationRecord
    has_one_attached :avatar

    def activate
        if self.active
            self.update(active: false)
        else
            self.update(active: true)
        end
    end

    def is_active
        if self.active
            return "Ativado"
        else
            return "Desativado"
        end
    end
end

app/models/plan.rb
class Plan < ApplicationRecord
end

app/models/service.rb
class Service < ApplicationRecord
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :validatable
end

app/models/welcome.rb
class Welcome < ApplicationRecord
    def activate
      Welcome.where(active: true).each do |w|
        w.update(active: false)
      end
  
      self.update(active: true)
    end

    def is_active
      if self.active
        return "Ativado"
      else
        return "Desativado"
      end
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
    id = params[:id]
    id = Base64::urlsafe_decode64(id)
    id = id[18, id.length - 1]
    client = Client.find(id)

    number = 24

    keys = [
      'A', 'B', 'C', 'D', 'E', 'F',
      'G', 'H', 'I', 'J', 'L', 'M',
      'N', 'O', 'P', 'Q', 'R', 'S',
      'T', 'U', 'V', 'X', 'Y', 'Z'
    ]

    keys.delete(client.key)
    number = number - 1

    options = [nil, nil, nil, nil, nil, nil, nil, nil, client.key]

    (0..7).each do |i|
      options[i] = keys[rand(number)]
      keys.delete(options[i])
      number = number - 1
    end

    if session[:id].blank?
      session[:id] = id
    end

    if session[:options].blank?
      session[:options] = options.shuffle
    elsif session[:id] != id
      session[:id] = id
      session[:attempts] = 0
      session[:options] = options.shuffle
    end

    @options = session[:options]
    @blocked = client.blocked
    @email = ContactInfo.find_by(active: true).email
  end

  def auth
    id = params[:id]
    id = Base64::urlsafe_decode64(id)
    id = id[18, id.length - 1]
    client = Client.find(id)
    product = client.product
    answer = params[:key]
    key = client.key

    if key == answer
      session[:attempts] = 0

      if product.match?(/https:\/\/app.powerbi.com\/view\?r=(\w+)/)
        product = product.match(/https:\/\/app.powerbi.com\/view\?r=(\w+)/)[1]
      end

      @product = product
    else
      if session[:attempts].blank?
        session[:attempts] = 1
      else
        session[:attempts] = session[:attempts] + 1
      end

      if session[:attempts] > 1
        client.update_attributes(blocked: true, authentication_failed: true)
        ClientsMailer.with(client: client).new_client_pass_link.deliver_later
      end

      redirect_to dashboard_path
    end
  end

  def authentication_failed
    id = params[:id]
    id = Base64::urlsafe_decode64(id)
    id = id[18, id.length - 1]
    client = Client.find(id)

    if client.blocked and client.authentication_failed
      keys = [
        'A', 'B', 'C', 'D', 'E', 'F',
        'G', 'H', 'I', 'J', 'L', 'M',
        'N', 'O', 'P', 'Q', 'R', 'S',
        'T', 'U', 'V', 'X', 'Y', 'Z'
      ]

      client.key = keys[rand(24)]

      session[:options] = nil
      session[:attempts] = 0

      client.update_attributes(blocked: false, authentication_failed: false)
      ClientsMailer.with(client: client).new_client_pass.deliver_later
    else
      redirect_to dashboard_path
    end
  end

  def example
    graph = Graph.find_by(active: true)
    product = graph.product

    if product.match?(/https:\/\/app.powerbi.com\/view\?r=(\w+)/)
      product = product.match(/https:\/\/app.powerbi.com\/view\?r=(\w+)/)[1]
    end

    @product = product
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  layout :resolve_layout

  def index
    @welcome = Welcome.find_by(active: true)
    graph = Graph.find_by(active: true)

    if graph.product.match?(/https:\/\/app.powerbi.com\/view\?r=(\w+)/)
      graph.product = graph.product.match(/https:\/\/app.powerbi.com\/view\?r=(\w+)/)[1]
    end

    @graph = graph
    @partners = Partner.where(active: :true)
    @contact = Contact.new
    @contact_info = ContactInfo.find_by(active: true)
    @address = Address.find_by(active: true)
    @members = Member.order(:id)
    @services = Service.order(:id)
    @another_services = Anotherservice.first
  end

  def page2
    @contact = Contact.new
  end

  def resolve_layout
    case action_name
    when 'index'
      'home'
    else
      'page2'
    end
  end

  #controller de welcomes
  # def create
  #    welcome = Welcome.new(welcome_params)
  #   if welcome.active
  #      welcome.activate
  #   end
  #
  # welcome.save
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def background_color
    case controller_name
    when 'sessions', 'passwords' then 'bg-dark'
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/dashboard/_blocked.html.erb
<main class="dashboard">
  <nav class="dashboard-navbar">
    <%= link_to '', root_path, class: 'dashboard-logo' %>
    <%= link_to 'dashboard' %>
  </nav>
  <div class="dashboard-powerbi">
    <main class='security'>
      <p class='security-title'>
        Seu acesso foi bloqueado
      </p>
      <p class='security-subtitle'>
        Isto pode ter acontecido porque alguém tentou acessar sua dashboard e errou a autenticação 2 ou mais vezes. Se este for o caso, você irá receber um email para redefinir sua insígnia e desbloquear sua dashboard. Se você não receber um email, entre em contato conosco através do email: <%= @email %>.
      </p>
    </main>
  </div>
  <footer class="dashboard-footer">
    &copy; 2019 Filterfeed Inc. All Rights Reserved
  </footer>
</main>

app/views/dashboard/_form.html.erb
<main class="dashboard">
  <nav class="dashboard-navbar">
    <%= link_to '', root_path, class: 'dashboard-logo' %>
    <%= link_to 'dashboard' %>
  </nav>
  <div class="dashboard-powerbi">
    <%= form_for :dashboard, url: dashboard_auth_path, html: {class: 'security'}, method: :post do |f| %>
      <%= f.hidden_field(:options, value: options) %>
      <p class='security-title'>Antes de prosseguir, precisamos<br />verificar sua identidade.</p>
      <p class='security-subtitle'>Selecione sua insígnia:</p>
      <table>
        <% options.each_slice(3) do |c1, c2, c3| %>
          <tr>
            <td class='security-td'><%= f.submit(c1, name: 'key', value: c1, class: 'security-button') %></td>
            <td class='security-td'><%= f.submit(c2, name: 'key', value: c2, class: 'security-button') %></td>
            <td class='security-td'><%= f.submit(c3, name: 'key', value: c3, class: 'security-button') %></td>
          </tr>
        <% end %>
      </table>
    <% end %>
  </div>
  <footer class="dashboard-footer">
    &copy; 2019 Filterfeed Inc. All Rights Reserved
  </footer>
</main>

app/views/dashboard/_powerbi.html.erb
<main class="dashboard">
  <nav class="dashboard-navbar">
    <%= link_to '', root_path, class: 'dashboard-logo' %>
    <%= link_to 'dashboard', dashboard_path %>
  </nav>
  <div class="dashboard-powerbi">
    <iframe src="https://app.powerbi.com/view?r=<%= product %>" frameborder="0" allowFullScreen="true"></iframe>
  </div>
  <footer class="dashboard-footer">
    &copy; 2019 Filterfeed Inc. All Rights Reserved
  </footer>
</main>

app/views/dashboard/auth.html.erb
<%= render partial: 'powerbi', locals: {product: @product} %>

app/views/dashboard/authentication_failed.html.erb
<main class="dashboard">
  <nav class="dashboard-navbar">
    <%= link_to '', root_path, class: 'dashboard-logo' %>
    <%= link_to 'dashboard' %>
  </nav>
  <div class="dashboard-powerbi">
    <main class='security'>
      <p class='security-title'>
        Sua insígnia foi redefinida
      </p>
      <p class='security-subtitle'>
        Em breve você receberá um email com a sua nova insígnia e um link para a sua dashboard.
      </p>
    </main>
  </div>
  <footer class="dashboard-footer">
    &copy; 2019 Filterfeed Inc. All Rights Reserved
  </footer>
</main>

app/views/dashboard/example.html.erb
<main class="dashboard">
  <nav class="dashboard-navbar">
    <%= link_to '', root_path, class: 'dashboard-logo' %>
    <%= link_to 'dashboard', dashboard_example_path(id: @product) %>
  </nav>
  <div class="dashboard-powerbi">
    <iframe src="https://app.powerbi.com/view?r=<%= @product %>" frameborder="0" allowFullScreen="true"></iframe>
  </div>
  <footer class="dashboard-footer">
    &copy; 2019 Filterfeed Inc. All Rights Reserved
  </footer>
</main>

app/views/dashboard/show.html.erb
<% if @blocked %>
  <%= render partial: 'blocked' %>
<% else %>
  <%= render partial: 'form', locals: {options: @options} %>
<% end %>