config/routes.rb
Rails.application.routes.draw do
  namespace :backoffice do
    root to: 'backoffice#index'
    resources :users, path: "administrators"
    resources :clients, path: "customers"
    resources :welcomes, path: "products_text"
    resources :graphs, path: "landing_page"
    resources :partners
    resources :plans
    resources :contact_infos, path: "contact"
    resources :addresses
    resources :members, path: "staff"
    resources :services, path: "products"
    resources :another_services, path: "staff_text"
    get '/dashboard', to: redirect('/backoffice'), as: 'redirect'
    post '/dashboard', to: 'backoffice#dashboard', as: 'dashboard'
  end

  namespace :backoffice do
    post '/clients/:id/block', to: 'clients#block', as: 'client_block'
    post '/welcomes/:id/activate', to: 'welcomes#activate', as: 'welcome_activate'
    post '/graphs/:id/activate', to: 'graphs#activate', as: 'graph_activate'
    post '/partners/:id/activate', to: 'partners#activate' , as: 'partner_activate'
    post '/plans/:id/activate', to: 'plans#activate', as: 'plan_activate'
    post '/contact_infos/:id/activate', to: 'contact_infos#activate', as: 'contact_info_activate'
    post '/addresses/:id/activate', to: 'addresses#activate', as: 'address_activate'
  end

  resources :dashboard, only: [:show]
  get '/dashboard', to: redirect('/')
  post '/dashboard/:id', to: 'dashboard#auth', as: 'dashboard_auth'
  get '/dashboard/:id/authentication_failed', to: 'dashboard#authentication_failed', as: 'dashboard_authentication_failed'

  devise_for :users

  get '/example', to: 'dashboard#example', as: 'dashboard_example'

  resources :contacts, only: [:create]

  root to: 'home#index'
  get '/curso', to: 'home#page2', as: 'home_curso'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/anotherservice.rb
class Anotherservice < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :emails, dependent: :destroy

  accepts_nested_attributes_for :emails, reject_if: :all_blank, allow_destroy: true

  private

  def send_confirmation
    ClientsMailer.with(client: self).create_client.deliver_later
  end
end

app/models/contact.rb
class Contact < MailForm::Base
    attribute :name,         :validate => true
    attribute :email,        :validate => true
    attribute :phone,        :validate => true
    attribute :message,      :validate => true
    attribute :nickname,     :captcha  => true

    def headers
        {
            :subject => "[CONTATO]",
            :to => "falecom@filterfeed.com.br",
            :from => %("#{name}" <#{email}>)
        }
    end
end

app/models/contact_info.rb
class ContactInfo < ApplicationRecord
end

app/models/email.rb
class Email < ApplicationRecord
  belongs_to :client
end

app/models/graph.rb
class Graph < ApplicationRecord
end

app/models/member.rb
class Member < ApplicationRecord
  has_one_attached :avatar
end

app/models/partner.rb
class Partner < ApplicationRecord
    has_one_attached :avatar

    def activate
        if self.active
            self.update(active: false)
        else
            self.update(active: true)
        end
    end

    def is_active
        if self.active
            return "Ativado"
        else
            return "Desativado"
        end
    end
end

app/models/plan.rb
class Plan < ApplicationRecord
end

app/models/service.rb
class Service < ApplicationRecord
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :validatable
end

app/models/welcome.rb
class Welcome < ApplicationRecord
    def activate
      Welcome.where(active: true).each do |w|
        w.update(active: false)
      end
  
      self.update(active: true)
    end

    def is_active
      if self.active
        return "Ativado"
      else
        return "Desativado"
      end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  layout :resolve_layout

  def index
    @welcome = Welcome.find_by(active: true)
    graph = Graph.find_by(active: true)

    if graph.product.match?(/https:\/\/app.powerbi.com\/view\?r=(\w+)/)
      graph.product = graph.product.match(/https:\/\/app.powerbi.com\/view\?r=(\w+)/)[1]
    end

    @graph = graph
    @partners = Partner.where(active: :true)
    @contact = Contact.new
    @contact_info = ContactInfo.find_by(active: true)
    @address = Address.find_by(active: true)
    @members = Member.order(:id)
    @services = Service.order(:id)
    @another_services = Anotherservice.first
  end

  def page2
    @contact = Contact.new
  end

  def resolve_layout
    case action_name
    when 'index'
      'home'
    else
      'page2'
    end
  end

  #controller de welcomes
  # def create
  #    welcome = Welcome.new(welcome_params)
  #   if welcome.active
  #      welcome.activate
  #   end
  #
  # welcome.save
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def background_color
    case controller_name
    when 'sessions', 'passwords' then 'bg-dark'
    end
  end
end

app/helpers/contact_infos_helper.rb
module ContactInfosHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/home/_graph.html.erb
<section class='cobertura'>
  <a class="anchor" id="cobertura"></a>
  <div id='cobertura-powerbi'>
    <iframe src='https://app.powerbi.com/view?r=<%= @graph.present? ? @graph.product : '' %>' frameborder='0' allowFullScreen='true'></iframe>
  </div>
</section>

app/views/home/_partners.html.erb
<div class="divisoria"></div>
<section class="section-partners">
  <a class="anchor" id="parceiros"></a>

  <div class="center-box">
    <h1 class="section-title" style="border-bottom: 3px solid #5e1cac;">PARC</h1>
    <h1 class="section-title">EIROS</h1>
  </div>

  <div class="center-box">
    <div class="partners-container">
      <% if @partners.present? %>
        <% @partners.each do |partner|%>
          <% if partner.avatar.attached?%>
            <div class="partners-box">
              <%= image_tag  partner.avatar.variant(resize: "250x100"), class:"redimension-img" %>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</section>

app/views/home/_plans.html.erb
<div class="section-plans">
  <a class="anchor" id="planos"></a>
  <div class='h-66 inherit'>
    <div>
      <h1> Planos </h1>
      <hr>
    </div>

    <div class="plans-subtitle">
      <b>-</b><span> MONTE SUA OPERAÇÃO </span><b>-</b>
    </div>

    <div class="plans-container">
      <% if plans.present? %>
        <% plans.each do |plan|  %>
          <%= link_to plan.content, "javascript:;", class: "plan-link link-unchecked"%>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/home/_welcome.html.erb
<section class="page-body"  id="page0">
  <div class="page-container">
  <nav class='header-navbar'>
    <ul class="horizontal-list">
      <li style="float: left;">
        <%= link_to root_path do%>
          <%= image_tag  "filterfeed.png", class:"logo-redimension" %>
        <% end %>
      </li>
      <li class="desktop-link" ><%= link_to  "contato", '#contato', class: "section-link" %></li>
      <li class="desktop-link" ><%= link_to  "planos", "#planos", class: "section-link" %></li>
      <li class="desktop-link" ><%= link_to  "parceiros", "#parceiros", class: "section-link" %></li>
      <li class="desktop-link" ><%= link_to  "cobertura", "#cobertura", class: "section-link" %></li>
      <li>
        <div class="dropdown">
          <a href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-bars"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
            <%= link_to  "cobertura", "#cobertura", class: "dropdown-item dropdown-link" %>
            <%= link_to  "parceiros", "#parceiros", class: "dropdown-item dropdown-link" %>
            <%= link_to  "planos", "#planos", class: "dropdown-item dropdown-link" %>
            <%= link_to  "contato", '#contato', class: "dropdown-item dropdown-link" %>
          </div>
        </div>
      </li>
    </ul>
  </nav>
  <div class="greetings-textbox">
    <p><%= @welcome.present? ? @welcome.content : '' %></p>
  </div>
</section>

app/views/home/index.html.erb
<section class="menu cid-qTkzRZLJNu" once="menu" id="menu1-0">
    <nav class="navbar navbar-expand beta-menu navbar-dropdown align-items-center navbar-fixed-top navbar-toggleable-sm bg-color transparent">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <div class="hamburger">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
            </div>
        </button>
        <div class="menu-logo">
            <div class="navbar-brand">
                <span class="navbar-logo">
                    <%= link_to root_path do %>
                        <%= image_tag "filterfeed.png", alt: "Filterfeed", style: "height: 3.8rem;" %>
                    <% end %>
                </span>
                <span class="navbar-caption-wrap"><a class="navbar-caption text-white display-4" href="https://mobirise.com"></a></span>
            </div>
        </div>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav nav-dropdown nav-right" data-app-modern-menu="true"><li class="nav-item">
                    <a id="color-link" class="nav-link link text-primary display-4" href="#produtos">

                        Produtos</a>
                </li><li class="nav-item"><a id="color-link" class="nav-link link text-primary display-4" href="#parceiros">

                        Parceiros<br></a></li><li class="nav-item"><a id="color-link" class="nav-link link text-primary display-4" href="#equipe">

                        Equipe</a></li><li class="nav-item"><a id="color-link" class="nav-link link text-primary display-4" href="#contato">

                        Contato</a></li></ul>

        </div>
    </nav>
</section>

<section class="cid-qTkA127IK8 mbr-fullscreen" id="header2-1">
    <%= video_tag "videos/autoplay.mp4", controls: false, autoplay: :autoplay, loop: :loop, mute: :mute, class: "video" %>
    <div class="container align-center">
        <div class="row justify-content-md-center">
            <div class="mbr-white col-md-10">
                <p id="center-text" class="mbr-text pb-3 mbr-fonts-style display-2"><%= @graph.present? ? @graph.name.html_safe : '' %></p>
                <div id="center-text" class="mbr-section-btn">
                    <% if @graph.present? %>
                        <% if @graph.link != nil and @graph.link != "" %>
                            <% if @graph.link != "#contato" %>
                                <%= link_to 'VER DASHBOARD', url_for(@graph.link), class: 'btn btn-md btn-secondary display-4' %>
                            <% else %>
                                <%= link_to 'SOLICITAR UMA DEMO', url_for(@graph.link), class: 'btn btn-md btn-secondary display-4' %>
                            <% end %>
                        <% else %>
                            <%= link_to 'VER DASHBOARD', dashboard_example_path(), class: 'btn btn-md btn-secondary display-4' %>
                        <% end %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
    <div class="mbr-arrow hidden-sm-down" aria-hidden="true">
        <a href="#content10-8">
            <i class="mbri-down mbr-iconfont"></i>
        </a>
    </div>
</section>

<section class="services1 cid-rwoBYlsokW" id="produtos">
    <!---->

    <!---->
    <!--Overlay-->

    <!--Container-->
    <div class="container">
        <div class="row justify-content-center">
            <!--Titles-->
            <div class="title pb-5 col-12"></div>
            <!--Card-1-->
            <% if @services.present? %>
                <% @services.each do |service| %>
                    <% if service.image.attached? %>
                        <div class="card col-12 col-md-6 p-3 col-lg-4">
                            <div class="card-wrapper">
                                <div class="card-img">
                                    <%= image_tag service.image %>
                                </div>
                                <div class="card-box">
                                    <h4 id="font-175-rem" class="card-title mbr-fonts-style display-5">
                                        <%= service.name.html_safe %>
                                    </h4>
                                    <p id="font-125-rem" class="mbr-text mbr-fonts-style display-7">
                                        <%= service.text.html_safe %>
                                    </p>
                                    <!--Btn-->
                                </div>
                            </div>
                        </div>
                    <% end %>
                <% end %>
            <% end %>
        </div>
    </div>
</section>

<section class="mbr-section article content10 cid-rwlE7l4Sv5" id="content10-8">
    <div class="container">
        <div class="inner-container" style="width: 66%;">
            <hr class="line" style="width: 25%;">
            <div class="section-text align-center mbr-white mbr-fonts-style display-5"><%= @welcome.present? ? @welcome.content.html_safe : '' %></div>
            <hr class="line" style="width: 25%;">
        </div>
    </div>
</section>

<section class="clients cid-rwlDTLEYCc" data-interval="false" id="clients-7">



        <div class="container mb-5">
            <div class="media-container-row">
                <div class="col-12 align-center">
                    <h2 class="mbr-section-title pb-3 mbr-fonts-style display-2">
                        Clientes e parceiros</h2>
                    <h3 class="mbr-section-subtitle mbr-light mbr-fonts-style display-5"></h3>
                </div>
            </div>
        </div>

    <div class="container">
        <div class="carousel slide" role="listbox" data-pause="true" data-keyboard="false" data-ride="carousel" data-interval="5000">
            <div class="carousel-inner" data-visible="5">
                <% if @partners.present? %>
                    <% @partners.each do |partner|%>
                        <% if partner.avatar.attached?%>
                            <div class="carousel-item ">
                                <div class="media-container-row">
                                    <div class="col-md-12">
                                        <div class="wrap-img ">
                                            <%= image_tag partner.avatar, class: "img-responsive clients-img" %>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <% end %>
                    <% end %>
                <% end %>
            </div>
            <div class="carousel-controls">
                <a data-app-prevent-settings="" class="carousel-control carousel-control-prev" role="button" data-slide="prev">
                    <span aria-hidden="true" class="mbri-left mbr-iconfont"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a data-app-prevent-settings="" class="carousel-control carousel-control-next" role="button" data-slide="next">
                    <span aria-hidden="true" class="mbri-right mbr-iconfont"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    </div>
</section>

<section class="team1 cid-rwm6mRgHK9" id="equipe">
    <div class="container align-center">
        <h2 class="pb-3 mbr-fonts-style mbr-section-title display-2">Equipe</h2>
        <h3 id="font-125-rem" class="pb-5 mbr-section-subtitle mbr-fonts-style mbr-light display-7"><%= @another_services.text.html_safe %></h3>
        <div class="row media-row">
            <% if @members.present? %>
                <% @members.each do |member| %>
                    <% if member.avatar.attached? %>
                        <div class="team-item col-lg-3 col-md-6">
                            <div class="item-image">
                                <%= image_tag member.avatar %>
                            </div>
                            <div class="item-caption py-3">
                                <div class="item-name px-2">
                                    <p class="mbr-fonts-style display-5">
                                        <%= member.name %>
                                    </p>
                                </div>
                                <div class="item-role px-2">
                                    <p><%= member.role %></p>
                                </div>
                                <div class="item-social pt-2">
                                    <%= link_to member.social do %>
                                        <span class="p-1 mbr-iconfont mbr-iconfont-social socicon-linkedin socicon" style="color: rgb(34, 10, 62); fill: rgb(34, 10, 62);"></span>
                                    <% end %>
                                </div>
                            </div>
                        </div>
                    <% end %>
                <% end %>
            <% end %>
        </div>
    </div>
</section>

<section class="mbr-section form4 cid-rwm6b0w00L" id="contato">




    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="google-map"><iframe frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/place?key=AIzaSyAEIpgj38KyLFELm2bK9Y7krBkz1K-cMq8&amp;q=place_id:ChIJ4X3xfq07WpMR-rLENmOFK0w" allowfullscreen=""></iframe></div>
            </div>
            <div class="col-md-6">

                <div>
                    <div class="icon-block pb-3 align-left">


                    </div>
                    <div class="icon-contacts pb-3">
                        <h5 class="align-left mbr-fonts-style display-7"><strong><%= @address ? @address.address1 : '' %></strong></h5>
                        <p class="mbr-text align-left mbr-fonts-style display-7"><%= @address ? @address.address2.html_safe : '' %></p>
                    </div>
                </div>
                <div data-form-type="formoid">
                    <%= render partial: "contacts/new", locals: {curso: false, contact: @contact, url: contacts_path, method: :post} %>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="cid-rwpwITgKue" id="social-buttons2-u">





    <div class="container">
        <div class="media-container-row">
            <div class="col-md-8 align-center">

                <div class="social-list pl-0 mb-0">
                    <a href="http://bit.ly/2YUuGpJ" target="_blank">
                        <span class="px-2 mbr-iconfont mbr-iconfont-social socicon-linkedin socicon"></span>
                    </a>
                    <a href="http://bit.ly/2SkUkkR" target="_blank">
                        <span class="px-2 mbr-iconfont mbr-iconfont-social socicon-facebook socicon"></span>
                    </a>
                    <a href="http://bit.ly/2YYujug" target="_blank">
                        <span class="px-2 mbr-iconfont mbr-iconfont-social socicon-instagram socicon"></span>
                    </a>
                    <a href="https://www.youtube.com/c/mobirise" target="_blank">

                    </a>
                    <a href="https://plus.google.com/u/0/+Mobirise" target="_blank">

                    </a>
                    <a href="https://www.behance.net/Mobirise" target="_blank">

                    </a>
                </div>
            </div>
        </div>
    </div>
</section>

<section once="footers" class="cid-rwm6sOygbQ" id="footer6-f">





    <div class="container">
        <div class="media-container-row align-center mbr-white">
            <div class="col-12">
                <p class="mbr-text mb-0 mbr-fonts-style display-7">
                    <strong><%= @contact_info ? @contact_info.phone : '' %></strong>
                    <br>
                    © Copyright&nbsp;2019 Filterfeed</p>
            </div>
        </div>
    </div>
</section>

app/views/home/index_old.html.erb
<%= render partial: "welcome" %>
<%= render partial: "graph" %>
<%= render partial: "partners" %>
<%= render partial: "home/plans", locals: {plans: @plans} %>
<%= render partial: "contacts/new", locals: {contact: @contact, url: contacts_path, method: :post, plans: @plans} %>