config/routes.rb
Rails.application.routes.draw do
  namespace :backoffice do
    root to: 'backoffice#index'
    resources :users, path: "administrators"
    resources :clients, path: "customers"
    resources :welcomes, path: "products_text"
    resources :graphs, path: "landing_page"
    resources :partners
    resources :plans
    resources :contact_infos, path: "contact"
    resources :addresses
    resources :members, path: "staff"
    resources :services, path: "products"
    resources :another_services, path: "staff_text"
    get '/dashboard', to: redirect('/backoffice'), as: 'redirect'
    post '/dashboard', to: 'backoffice#dashboard', as: 'dashboard'
  end

  namespace :backoffice do
    post '/clients/:id/block', to: 'clients#block', as: 'client_block'
    post '/welcomes/:id/activate', to: 'welcomes#activate', as: 'welcome_activate'
    post '/graphs/:id/activate', to: 'graphs#activate', as: 'graph_activate'
    post '/partners/:id/activate', to: 'partners#activate' , as: 'partner_activate'
    post '/plans/:id/activate', to: 'plans#activate', as: 'plan_activate'
    post '/contact_infos/:id/activate', to: 'contact_infos#activate', as: 'contact_info_activate'
    post '/addresses/:id/activate', to: 'addresses#activate', as: 'address_activate'
  end

  resources :dashboard, only: [:show]
  get '/dashboard', to: redirect('/')
  post '/dashboard/:id', to: 'dashboard#auth', as: 'dashboard_auth'
  get '/dashboard/:id/authentication_failed', to: 'dashboard#authentication_failed', as: 'dashboard_authentication_failed'

  devise_for :users

  get '/example', to: 'dashboard#example', as: 'dashboard_example'

  resources :contacts, only: [:create]

  root to: 'home#index'
  get '/curso', to: 'home#page2', as: 'home_curso'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/backoffice/addresses_controller.rb
class Backoffice::AddressesController < Backoffice::BackofficeController

    def index
        @addresses = Address.order(active: :desc).order(:id)
    end

    def new
        @address = Address.new
    end

    def create
        @address = Address.new(address_params)

        if @address.save
            if @address.active
                activating(@address)
            end
            flash[:success] = 'Texto criado com sucesso!'
            redirect_to backoffice_addresses_path
        else
            flash[:error] = 'Erro ao criar o texto'
            render :new
        end
    end

    def edit
        @address = Address.find(params[:id])
    end

    def update
        @address = Address.find(params[:id])

        if @address.update(address_params)
            if @address.active
                activating(@address)
            end
            flash[:success] = 'Texto atualizado com sucesso!'
            redirect_to backoffice_addresses_path
        else
            flash[:error] = 'Erro ao atualizar o texto'
            render :edit
        end
    end

    def destroy
        @address = Address.find(params[:id])

        if @address.destroy
            flash[:success] = 'Texto excluído com sucesso!'
            redirect_to backoffice_addresses_path
        else
            flash[:error] = 'Erro ao excluir o texto'
            render :index
        end
    end

    def activate
        activating(Address.find(params[:id]))

        redirect_to backoffice_addresses_path
    end


    private
    def activating(address)
        if(address.active)
            address.update(active: false)
        else
            Address.all.where("active = true").each do |a|
                if a != address
                    a.update(active: false)
                end
            end
            address.update(active: true)
        end
    end

    def address_params
        params.require(:address).permit(:address1, :address2, :active)
    end
end

app/controllers/backoffice/another_services_controller.rb
class Backoffice::AnotherServicesController < Backoffice::BackofficeController
  def index
    @another_services = Anotherservice.order(:id)
  end

  def new
    @another_service = Anotherservice.new
  end

  def create
    another_service = Anotherservice.new(another_service_params)

    if another_service.save
      flash[:success] = 'Produto cadastrado com sucesso!'
      redirect_to backoffice_another_services_path
    else
      flash[:error] = 'Erro ao cadastrar novo produto!'
      render :new
    end
  end

  def edit
    @another_service = Anotherservice.find(params[:id])
  end

  def update
    another_service = Anotherservice.find(params[:id])

    if another_service.update(another_service_params)
      flash[:success] = 'Produto editado com sucesso!'
      redirect_to backoffice_another_services_path
    else
      flash[:error] = 'Não foi possível editar o produto!'
      render :edit
    end
  end

  def destroy
    another_service = Anotherservice.find(params[:id])

    if another_service.destroy
      flash[:success] = 'Produto excluído com sucesso!'
      redirect_to backoffice_another_services_path
    else
      flash[:error] = 'Não foi possível excluir o produto!'
      redirect_to backoffice_another_services_path
    end
  end

  private

  def another_service_params
    params.require(:anotherservice).permit(:name, :text)
  end
end

app/controllers/backoffice/backoffice_controller.rb
class Backoffice::BackofficeController < ApplicationController
  before_action :authenticate_user!

  layout 'backoffice/backoffice'

  def index
    redirect_to backoffice_graphs_path
  end

  def dashboard
    url = params[:encode][:url]
    if url.match?(/https:\/\/app.powerbi.com\/view\?r=(\w+)/)
      url = url.match(/https:\/\/app.powerbi.com\/view\?r=(\w+)/)[1]
      url = Base64::urlsafe_encode64(url, padding: false)
      @url_encoded = dashboard_url(url)
    else
      redirect_to backoffice_root_path
    end
  end

  private

  def authenticate_admin!
    redirect_to backoffice_root_path unless current_user.admin
  end
end

app/controllers/backoffice/clients_controller.rb
class Backoffice::ClientsController < Backoffice::BackofficeController
  def index
    @clients = Client.order(:id)
  end

  def new
    @client = Client.new
    @client.emails.build
  end

  def create
    keys = [
      'A', 'B', 'C', 'D', 'E', 'F',
      'G', 'H', 'I', 'J', 'L', 'M',
      'N', 'O', 'P', 'Q', 'R', 'S',
      'T', 'U', 'V', 'X', 'Y', 'Z'
    ]

    client = Client.new(client_params)
    client.key = keys[rand(24)]

    if client.save
      flash[:success] = 'Cliente cadastrado com sucesso!'
      ClientsMailer.with(client: client).create_client.deliver_later
      redirect_to backoffice_clients_path
    else
      flash[:erro] = 'Erro ao cadastrar o cliente!'
      render :new
    end
  end

  def edit
    @client = Client.find(params[:id])
  end

  def update
    id = params[:id]
    client = Client.find(id)

    old_emails = []

    client.emails.each do |e|
      old_emails.append(e.address)
    end

    if client.update(client_params)
      flash[:success] = 'Cadastro do cliente atualizado com sucesso!'

      new_emails = []

      client.emails.each do |e|
        new_emails.append(e.address)
      end

      if new_emails.sort != old_emails.sort
        ClientsMailer.with(client: client).create_client.deliver_later
      end

      redirect_to backoffice_clients_path
    else
      flash[:erro] = 'Erro ao atualizar o cadastro do cliente!'
      render :new
    end
  end

  def destroy
    client = Client.find(params[:id])

    if client.destroy
      flash[:success] = 'Cliente excluído com sucesso!'
      redirect_to backoffice_clients_path
    else
      flash[:erro] = 'Erro ao excluir o cliente!'
      render :index
    end
  end

  def block
    blocking(Client.find(params[:id]))

    redirect_to backoffice_clients_path
  end

  private

  def blocking(client)
    if(client.blocked)
      client.update(blocked: false)
    else
      client.update(blocked: true)
    end
  end

  def client_params
    params.require(:client).permit(:name, :cnpj, :phone, :product, emails_attributes: [:id, :address, :_destroy])
  end
end

app/controllers/backoffice/contact_infos_controller.rb
class Backoffice::ContactInfosController < Backoffice::BackofficeController

    def index
        @contact_infos = ContactInfo.order(active: :desc).order(:id)
    end

    def new
        @contact_info = ContactInfo.new
    end

    def create
        @contact_info = ContactInfo.new(info_params)
        if @contact_info.save
            if @contact_info.active == true
                activating(@contact_info)
            end
            flash[:success] = 'Novo texto salvo com sucesso!'
            redirect_to backoffice_contact_infos_path
        else
            flash[:error] = 'Erro ao salvar o texto!'
            render :new
        end
    end

    def edit
        @contact_info = ContactInfo.find(params[:id])
    end

    def update
        @contact_info = ContactInfo.find(params[:id])

        if @contact_info.update(info_params)
            if @contact_info.active
                activating(@contact_info)
            end
            flash[:success] = 'Texto atualizado com sucesso!'
            redirect_to backoffice_contact_infos_path
        else
            flash[:error] = 'Erro ao salvar o texto'
            render :edit
        end
    end

    def destroy
        @contact_info = ContactInfo.find(params[:id])

        if @contact_info.destroy
            flash[:success] = 'Texto excluído com sucesso!'
            redirect_to backoffice_contact_infos_path
        else
            flash[:error] = 'Erro ao excluir o texto'
            render :index
        end
    end

    def activate
        activating(ContactInfo.find(params[:id]))

        redirect_to backoffice_contact_infos_path
    end

    private

    def activating(info)
        if(info.active)
            info.update(active: false)
        else
            ContactInfo.all.where("active = true").each do |c|
                if c != info
                    c.update(active: false)
                end
            end
            info.update(active: true)
        end
    end

    def info_params
        params.require(:contact_info).permit(:email, :phone, :active)
    end
end

app/controllers/backoffice/graphs_controller.rb
class Backoffice::GraphsController < Backoffice::BackofficeController
  def index
    @graphs = Graph.order(active: :desc).order(:id)
  end

  def new
    @graph = Graph.new()
  end

  def create
    graph = Graph.new(graphs_params)

    if graph.save
      redirect_to backoffice_graphs_path
    else
      render :new
    end
  end

  def edit
    @graph = Graph.find(params[:id])
  end

  def update
    graph = Graph.find(params[:id])

    if graph.update(graphs_params)
      redirect_to backoffice_graphs_path
    else
      render :edit
    end
  end

  def destroy
    graph = Graph.find(params[:id])

    if graph.destroy
      redirect_to backoffice_graphs_path
    else
      render :edit
    end
  end

  def activate
    activating(Graph.find(params[:id]))

    redirect_to backoffice_graphs_path
  end

  private

  def activating(graph)
    if(graph.active)
      graph.update(active: false)
    else
      Graph.all.where(active: true).each do |g|
        g.update(active: false)
      end
      graph.update(active: true)
    end
  end

  def graphs_params
    params.require(:graph).permit(:name, :link, :product, :active)
  end

end

app/controllers/backoffice/members_controller.rb
class Backoffice::MembersController < Backoffice::BackofficeController
  def index
    @members = Member.order(:id)
  end

  def new
    @member = Member.new
  end

  def create
    member = Member.new(member_params)

    if member.save
      flash[:success] = 'Membro cadastrado com sucesso!'
      redirect_to backoffice_members_path
    else
      flash[:error] = 'Erro ao cadastrar novo membro!'
      render :new
    end
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    member = Member.find(params[:id])

    if member.update(member_params)
      flash[:success] = 'Membro editado com sucesso!'
      redirect_to backoffice_members_path
    else
      flash[:error] = 'Não foi possível editar o membro!'
      render :edit
    end
  end

  def destroy
    member = Member.find(params[:id])

    if member.destroy
      flash[:success] = 'Membro excluído com sucesso!'
      redirect_to backoffice_members_path
    else
      flash[:error] = 'Não foi possível excluir o membro!'
      redirect_to backoffice_members_path
    end
  end

  private

  def member_params
    params.require(:member).permit(:name, :role, :social, :avatar)
  end
end

app/controllers/backoffice/partners_controller.rb
class Backoffice::PartnersController < Backoffice::BackofficeController
    before_action :current_partner, only: [:show, :edit, :update, :destroy, :activate]

    def index
        @partners = Partner.order(active: :desc)
    end

    def show

    end

    def new
        @partner = Partner.new
    end

    def create
        partner = Partner.create(partner_params)

        redirect_to backoffice_partners_path
    end

    def edit; end

    def update
        @partner.update(partner_params)

        redirect_to backoffice_partners_path
    end

    def destroy
        @partner.destroy

        redirect_to backoffice_partners_path
    end

    def activate
        @partner.activate

        redirect_to backoffice_partners_path
    end

    private

    def partner_params
        params.require(:partner).permit(:name, :avatar, :active)
    end

    def current_partner
        @partner = Partner.find(params[:id])
    end

end

app/controllers/backoffice/plans_controller.rb
class Backoffice::PlansController < Backoffice::BackofficeController

    def index
        @plans = Plan.order(active: :desc).order(:id)
    end

    def new
        @plan = Plan.new
    end

    def create
        @plan = Plan.new(plan_params)

        if @plan.save
            if @plan.active
                activating(@plan)
            end
            flash[:success] = 'Plano criado com sucesso!'
            redirect_to backoffice_plans_path
        else
            flash[:error] = 'Erro ao criar o plano'
            render :new
        end
    end

    def edit
        @plan = Plan.find(params[:id])
    end

    def update
        @plan = Plan.find(params[:id])

        if @plan.update(plan_params)
            if @plan.active
                activating(@plan)
            end
            flash[:success] = 'Plano atualizado com sucesso!'
            redirect_to backoffice_plans_path
        else
            flash[:error] = 'Erro ao atualizar o plano'
            render :edit
        end
    end

    def destroy
        @plan = Plan.find(params[:id])

        if @plan.destroy
            flash[:success] = 'Plano excluído com sucesso!'
            redirect_to backoffice_plans_path
        else
            flash[:error] = 'Erro ao excluir o plano'
            render :index
        end
    end

    def activate
        activating(Plan.find(params[:id]))

        redirect_to backoffice_plans_path
    end


    private
    def activating(plan)
        if(plan.active)
            plan.update(active: false)
        else
            plan.update(active: true)
        end
    end

    def plan_params
        params.require(:plan).permit(:content, :active)
    end

end

app/helpers/backoffice/another_services_helper.rb
module Backoffice::AnotherServicesHelper
end

app/helpers/backoffice/backoffice_helper.rb
module Backoffice::BackofficeHelper
  def active?(path)
    'active' if current_page?(path)
  end

  def breadcrumbs
    controller = {'another_services' => 'Texto (Equipe)', 'services' => 'Produtos', 'members' => 'Equipe', 'graphs' => 'Landing Page', 'clients' => 'Clientes', 'backoffice' => 'Dashboard', 'users' => 'Gerentes', 'welcomes' => 'Texto (Produtos)', 'partners' => 'Parceiros' , 'plans' => "Planos", 'contact_infos' => 'Contato', 'addresses' => 'Endereços'}
    action = {'dashboard' => 'Resultado', 'new' => 'Cadastrar', 'edit' => 'Editar'}
    path = {'backoffice' => backoffice_root_path, 'users' => backoffice_users_path}

    case action_name
    when 'new', 'edit', 'dashboard' then
      breadcrumbs = "<li class='breadcrumb-item'>
                        #{link_to(controller[controller_name], path[controller_name])}
                      </li>"

      breadcrumbs += "<li class='breadcrumb-item active'>
                        #{action[action_name]}
                      </li>"

    else
      breadcrumbs = "<li class='breadcrumb-item active'>
                      #{controller[controller_name]}
                    </li>"

    end

    breadcrumbs.html_safe
  end
end

app/helpers/backoffice/clients_helper.rb
module Backoffice::ClientsHelper
end

app/helpers/backoffice/graphs_helper.rb
module Backoffice::GraphsHelper
end

app/helpers/backoffice/members_helper.rb
module Backoffice::MembersHelper
end

app/helpers/backoffice/partners_helper.rb
module Backoffice::PartnersHelper
end

app/helpers/backoffice/services_helper.rb
module Backoffice::ServicesHelper
end

app/helpers/backoffice/users_helper.rb
module Backoffice::UsersHelper
end

app/views/layouts/backoffice/_breadcumbs.html.erb
<ol class='breadcrumb'>
  <%= breadcrumbs %>
</ol>

app/views/layouts/backoffice/_sidebar.html.erb
<ul class='sidebar navbar-nav'>
  <li class='nav-item <%= active?(backoffice_graphs_path) %>'>
    <%= link_to(backoffice_graphs_path, class: 'nav-link') do %>
      <i class='far fa-fw fa-window-maximize'></i>
      <span>Landing Page</span>
    <% end %>
  </li>
  <li class='nav-item <%= active?(backoffice_services_path) %>'>
    <%= link_to(backoffice_services_path, class: 'nav-link') do %>
      <i class='fas fa-fw fa-project-diagram'></i>
      <span>Produtos</span>
    <% end %>
  </li>
  <li class='nav-item <%= active?(backoffice_welcomes_path) %>'>
    <%= link_to(backoffice_welcomes_path, class: 'nav-link') do %>
      <i class='fas fa-fw fa-align-justify'></i>
      <span>Texto (Produtos)</span>
    <% end %>
  </li>
  <li class='nav-item <%= active?(backoffice_partners_path) %>'>
    <%= link_to(backoffice_partners_path, class: 'nav-link') do %>
      <i class='fas fa-fw fa-handshake'></i>
      <span>Parceiros</span>
    <% end %>
  </li>
  <li class='nav-item <%= active?(backoffice_members_path) %>'>
    <%= link_to(backoffice_members_path, class: 'nav-link') do %>
      <i class='fas fa-fw fa-users'></i>
      <span>Equipe</span>
    <% end %>
  </li>
  <li class='nav-item <%= active?(backoffice_another_services_path) %>'>
    <%= link_to(backoffice_another_services_path, class: 'nav-link') do %>
      <i class='fas fa-fw fa-align-justify'></i>
      <span>Texto (Equipe)</span>
    <% end %>
  </li>
  <li class='nav-item <%= active?(backoffice_addresses_path) %>'>
    <%= link_to(backoffice_addresses_path, class: 'nav-link') do %>
      <i class='fas fa-fw fa-map-marked-alt'></i>
      <span>Endereços</span>
    <% end %>
  </li>
  <li class='nav-item <%= active?(backoffice_contact_infos_path) %>'>
    <%= link_to(backoffice_contact_infos_path, class: 'nav-link') do %>
      <i class='fas fa-fw fa-phone'></i>
      <span>Contato</span>
    <% end %>
  </li>
  <!-- <li class='nav-item <%= active?(backoffice_plans_path) %>'>
    <%= link_to(backoffice_plans_path, class: 'nav-link') do %>
      <i class='fas fa-fw fa-clipboard-list'></i>
      <span>Planos</span>
    <% end %>
  </li> -->
  <% if current_user.admin %>
    <li class='nav-item <%= active?(backoffice_users_path) %>'>
      <%= link_to(backoffice_users_path, class: 'nav-link') do %>
        <i class='fas fa-fw fa-user'></i>
        <span>Gerentes</span>
      <% end %>
    </li>
    <li class='nav-item <%= active?(backoffice_clients_path) %>'>
      <%= link_to(backoffice_clients_path, class: 'nav-link') do %>
        <i class='fas fa-fw fa-hand-holding-usd'></i>
        <span>Clientes</span>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/layouts/backoffice/backoffice.html.erb
<!DOCTYPE html>

<html lang='en'>
  <head>
    <title>Filterfeed</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag asset_path('favicon.png') %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_link_tag 'css/sb-admin.css' %>
    <%= javascript_include_tag 'js/sb-admin.js' %>
  </head>
  <body id='page-top' class='backoffice'>
    <nav class='navbar navbar-expand navbar-dark bg-color static-top'>
      <%= link_to(root_path, class: 'd-flex align-items-center') do %>
        <div class='backoffice-logo'></div>
      <% end %>

      <!-- Navbar -->
      <ul class='navbar-nav ml-auto md-0'>
        <li class='nav-item active'>
          <%= link_to(destroy_user_session_path(), class: 'nav-link', method: :delete) do %>
            <i class='fas fa-fw fa-sign-out-alt'></i>
            <span>Logout<span>
          <% end %>
        </li>
      </ul>
    </nav>

    <div id='wrapper'>
      <%= render 'layouts/backoffice/sidebar' %>

      <div class='px-3 pt-3 w-100' style='height: 100%'>
        <% flash.each do |key, value| %>
            <% if key == "error" %>
              <div class="alert alert-error"><%= value %></div>
            <% elsif key == "notice" %>
              <div class="alert alert-success"><%= value %></div>
            <% else %>
              <div class="alert alert-warning"><%= value %></div>
            <% end %>
        <% end %>
        <%= render 'layouts/backoffice/breadcumbs' %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>